steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/audio-splitter', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/audio-splitter']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'audio-splitter'
      - '--image=gcr.io/$PROJECT_ID/audio-splitter'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=600'
      - '--max-instances=10'
      - '--set-env-vars=FLASK_MAX_CONTENT_LENGTH=524288000,GUNICORN_TIMEOUT=600'