[run]
command = "gunicorn --bind 0.0.0.0:5000 --reuse-port --reload main:app"

[deployment]
run = ["./start.sh"]
deploymentTarget = "cloudrun"

[deployment.cloudRunOptions]
memory = "2Gi"
cpu = "2"
maxScale = 10
minScale = 1
concurrency = 10

[deployment.env]
PYTHONPATH = "."
GUNICORN_CMD_ARGS = "--timeout 600 --max-requests 1000 --limit-request-line 8190 --limit-request-field_size 8190"
FLASK_MAX_CONTENT_LENGTH = "209715200"
REPLIT_DEPLOYMENT = "1"

[nix]
channel = "stable-24.05"

[nix.uv]
enable = true

[[ports]]
localPort = 5000
externalPort = 80

[env]
SESSION_SECRET = "your_session_secret_here"